### ISSUE TITLE
Not getting execution_id for frame

### ISSUE THREAD

**Issue by hkmaly** [rubycdp/ferrum#235] opened 2021-12-29 10:31 UTC
Is there anything you can do with (i)frame not getting execution_id if, based on running the script with FERRUM_DEBUG=true, the Runtime.executionContextCreated never happens for that frame? Or is that chromium bug?

(Note: Found a workaround how to do what I needed without accessing frame, but I'm still interested ...)

**Comment by route** [comment] 2021-12-29 12:54
You better provide log, because it's hard to figure out without data

**Comment by hkmaly** [comment] 2021-12-30 03:42
Sorry, I don't want to public the page it's happening on and it's apparent it's caused by something specific it does as it works on other pages. (And it does a LOT of things. Including creating three frames despite only one being visible in DOM.)

But looking into the source, I noticed that only way how execution_id can be filled is as reaction on Runtime.executionContextCreated ... and that one is never called ...

**Comment by route** [comment] 2021-12-30 06:39
I helpless here then.

**Comment by skyeagle** [comment] 2023-01-10 22:01
We have hit the same issue, `execution_id` is not getting set in headful mode.

It's easy to reproduce with the following spec:

```sh
HEADLESS=false bundle exec rspec spec/frame_spec.rb
```
Can we re-open this issue? I would be happy to provide any additional information for further investigation if needed. Thanks!

**Comment by route** [comment] 2023-01-11 14:19
@skyeagle can you show the error you are getting running the command you provided?

**Comment by skyeagle** [comment] 2023-01-11 15:43
> @skyeagle can you show the error you are getting running the command you provided?

Sure thing

```sh
  1) Ferrum::Frame supports selection by index
     Failure/Error: expect(frame.url).to end_with("/ferrum/slow")

     NoMethodError:
       undefined method `url' for nil:NilClass
```
There is chrome's version on Mac OS X M1
```
Version 109.0.5414.87 (Official Build) (arm64)
```

Thank you for taking a look!

**Comment by hkmaly** [comment] 2023-01-23 18:16
... I was running the browser in head-ful mode ...

**Comment by KevUp** [comment] 2023-02-21 11:38
Also seeing issue when running Capybara / Cuprite tests in head-ful mode, fine in headless.

test is using  within_frame frame do block

/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/ferrum-0.13/lib/ferrum/page.rb:414: warning: Capybara::Cuprite::Page#execution_id! at /Users/UpstilK/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:138 forwarding to private method NilClass#execution_id!

NoMethodError: undefined method `execution_id!' for nil:NilClass

      unless defined?(methods.each)
                             ^^^^^
/Users/UpstilK/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:236:in `execution_id!'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/ferrum-0.13/lib/ferrum/page.rb:414:in `block in inject_extensions'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/ferrum-0.13/lib/ferrum/page.rb:407:in `each'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/ferrum-0.13/lib/ferrum/page.rb:407:in `inject_extensions'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/cuprite-0.14.3/lib/capybara/cuprite/page.rb:119:in `switch_to_frame'
/Users/UpstilK/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `switch_to_frame'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/cuprite-0.14.3/lib/capybara/cuprite/driver.rb:107:in `switch_to_frame'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/capybara-3.38.0/lib/capybara/session.rb:410:in `switch_to_frame'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/capybara-3.38.0/lib/capybara/session.rb:448:in `within_frame'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/capybara-3.38.0/lib/capybara/dsl.rb:52:in `call'
/Users/UpstilK/.rvm/gems/ruby-3.1.2/gems/capybara-3.38.0/lib/capybara/dsl.rb:52:in `within_frame'

**Comment by infernalmaster** [comment] 2023-06-27 13:29
I'm using chrome `Version 114.0.5735.133 (Official Build) (arm64)` and also have same issue. I tried to debug and notices that `Page.frameAttached` was triggered for iframe after that `Page.frameDetached` removed iframe from `page.driver.browser.page.frames`.

I found similar issue for puppeteer https://github.com/puppeteer/puppeteer/issues/2548.
There was proposed flag `--disable-features=site-per-process` but ferrum already has it in `lib/ferrum/browser/options/chrome.rb`

Also there was a link to some chromium issue
https://bugs.chromium.org/p/chromium/issues/detail?id=924937#c13


Looks like puppeteer implemented that change in this PR https://github.com/puppeteer/puppeteer/pull/7556 but it would requires multiple changes in out case.

So I also checked capybara and found that they [use](https://github.com/teamcapybara/capybara/blob/5521da18729c3337d63351e7c4a59faf13538837/lib/capybara/registrations/drivers.rb#L38) `--disable-site-isolation-trials` and it helped.

Right now my cuprit initialization looks like that


```
Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(app,
    headless: Capybara.headless?,
    inspector: true,
    timeout: 30,
    process_timeout: 30,
    browser_options: Hash.new.tap do |hash|
      hash['no-sandbox'] = nil if Capybara.no_sandbox?
      hash['headless'] = 'new' if Capybara.headless?

      # Required for cuprite to work with iframes
      hash['disable-site-isolation-trials'] = nil
```

**Comment by route** [comment] 2024-02-06 08:46
It should work now in the master as I merged work on `disable-site-isolation-trials`

**Closed by route** 2024-02-06 08:46 UTC

**Comment by o0101** [comment] 2024-05-24 11:49
@infernalmaster this is excellent research, thank you. 😄
